# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 13df527a7fd9b26fd491779d33c7ca4d4662bc116ec461fa8bd6b37c6c158cd6cd6be891565f5ca10867949d653a08e102a5c9fb925ede76e81f09c0a29c2531

test:
  secret_key_base: 267db18506bf04e84d35d35e3bc314d2b5b2036c8e5da31a98b2c5e449c79c7d69c9d019b1913426f0b653a25c59c161795646c061db25502f1d692c649cabf2

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
